name: "LoudLlama Dashboard"
version: "0.5.0"
slug: "loudllama_dashboard"
description: "Build your own freely customizable, iPad-style dashboard in Home Assistant with movable widgets"
url: "https://github.com/loudllama/loudllama-dashboard"
arch:
  - amd64
  - aarch64
  - armv7
init: false
ingress: true
ingress_port: 8099
ingress_stream: false
panel_icon: mdi:view-dashboard-variant
panel_title: "LoudLlama Dashboard"
homeassistant_api: true
hassio_api: true
hassio_role: default
map:
  - addon_config:rw
  - share:rw
options: {}
schema: {}
